//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InsuranceEntities : DbContext
    {
        public InsuranceEntities()
            : base("name=InsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_participants> tbl_participants { get; set; }
        public virtual DbSet<tbl_participantType> tbl_participantType { get; set; }
        public virtual DbSet<tbl_policies> tbl_policies { get; set; }
        public virtual DbSet<tbl_policyType> tbl_policyType { get; set; }
    
        public virtual int usp_addParticipant(string firstname, string lastname, string middlename, Nullable<System.DateTime> dob, Nullable<int> participantTypeNo)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var participantTypeNoParameter = participantTypeNo.HasValue ?
                new ObjectParameter("participantTypeNo", participantTypeNo) :
                new ObjectParameter("participantTypeNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_addParticipant", firstnameParameter, lastnameParameter, middlenameParameter, dobParameter, participantTypeNoParameter);
        }
    
        public virtual int USP_POLOCIES(Nullable<int> policyno, string planno, Nullable<double> installement, string insured, Nullable<double> assured, string status, string mode, Nullable<System.DateTime> due, string benfit, string action)
        {
            var policynoParameter = policyno.HasValue ?
                new ObjectParameter("policyno", policyno) :
                new ObjectParameter("policyno", typeof(int));
    
            var plannoParameter = planno != null ?
                new ObjectParameter("planno", planno) :
                new ObjectParameter("planno", typeof(string));
    
            var installementParameter = installement.HasValue ?
                new ObjectParameter("installement", installement) :
                new ObjectParameter("installement", typeof(double));
    
            var insuredParameter = insured != null ?
                new ObjectParameter("insured", insured) :
                new ObjectParameter("insured", typeof(string));
    
            var assuredParameter = assured.HasValue ?
                new ObjectParameter("assured", assured) :
                new ObjectParameter("assured", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var modeParameter = mode != null ?
                new ObjectParameter("mode", mode) :
                new ObjectParameter("mode", typeof(string));
    
            var dueParameter = due.HasValue ?
                new ObjectParameter("due", due) :
                new ObjectParameter("due", typeof(System.DateTime));
    
            var benfitParameter = benfit != null ?
                new ObjectParameter("benfit", benfit) :
                new ObjectParameter("benfit", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_POLOCIES", policynoParameter, plannoParameter, installementParameter, insuredParameter, assuredParameter, statusParameter, modeParameter, dueParameter, benfitParameter, actionParameter);
        }
    
        public virtual int usp_updateParticipantDetails(string firstname, string lastname, string middlename, Nullable<System.DateTime> dob, Nullable<int> id)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_updateParticipantDetails", firstnameParameter, lastnameParameter, middlenameParameter, dobParameter, idParameter);
        }
    
        public virtual int usp_viewParticipant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_viewParticipant");
        }
    
        public virtual ObjectResult<string> usp_beneficiary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_beneficiary");
        }
    
        public virtual ObjectResult<string> usp_insured()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_insured");
        }
    
        public virtual ObjectResult<string> usp_owner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_owner");
        }
    }
}
