//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_policies
    {
        public int PolicyNumber { get; set; }

        [Required(ErrorMessage = "Plan Number is required.")]
        public Nullable<int> PlanNumber { get; set; }

        [Required(ErrorMessage = "Installment Premium is required.")]
        [Display(Name ="Installment Premium")]
        //How much amount one need to pay for single premium
        public Nullable<double> InstallementPremium { get; set; }

        [Required(ErrorMessage ="Isured is Required.")]
        public string Insured { get; set; }

        [Required]
        public Nullable<double> SumAssured { get; set; }

        [Required]
        public string PolicyStatus { get; set; }

        [Required]
        public string PremiumMode { get; set; }

        [Required]
        public Nullable<System.DateTime> PremiumDueDate { get; set; }

        [Required]
        public string Beneficiary { get; set; }

        [Required]
        public string Owner { get; set; }

        [Required]
        public string PolicyTerm { get; set; }
    
        public virtual tbl_policyType tbl_policyType { get; set; }
    }
}
